[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tuya-vacuum"
version = "0.1.9"
description = "A python library to view maps from Tuya robot vacuums"
authors = [
    { name = "Jaiden Labelle", email = "jaidenjlabelle@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "httpx>=0.27",
    "numpy>=2.1",
    "pillow>=11.0",
    "six>=1.16",
]

[project.urls]
Homepage = "https://github.com/jaidenlabelle/tuya-vacuum"
Issues = "https://github.com/jaidenlabelle/tuya-vacuum/issues"

[tool.pytest.ini_options]
markers = [
    "functional: mark a test as functional (can be slow or require external resources)",
]

[tool.ruff.lint]
extend-select = ["PLE"]

[tool.ruff.flake8-quotes]
multiline-quotes = "double"
docstring-quotes = "double"
inline-quotes = "double"