"""The Layout class."""

import logging
import re

import numpy as np
from PIL import Image, ImageColor

from tuya_vacuum.const import (
    BITMAP_TYPE_HEX_MAP,
    ORIGIN_MAP_COLOR,
    pixel_types,
)
from tuya_vacuum.lz4 import uncompress
from tuya_vacuum.map.room import Room
from tuya_vacuum.utils import (
    chunks,
    combine_high_low_to_int,
    hex_to_ints,
    shrink_number,
)

# Length of map header in bytes
MAP_HEADER_LENGTH = 48

# Length of the map header in bytes for version 152.
# This version has no total_count/length_after_compression fields - the
# compressed bitmap starts right after pile_y.
MAP_HEADER_LENGTH_V152 = 36

_LOGGER = logging.getLogger(__name__)


class Layout:
    """The layout map of a home generated by a vacuum cleaner."""

    def __init__(self, data: bytes) -> None:
        """Parse the data of a vacuum's layout map.

        @param data: Raw bytes of the layout map.
        """
        _LOGGER.debug("Parsing layout")

        self.raw = data

        hex_data = data.hex()

        # Parse the header of the map
        self._parse_header(hex_data[:MAP_HEADER_LENGTH])

        # Invalid map type
        if self.type > 255:
            raise RuntimeError(f"Map layout header type: {self.type} is not valid.")

        # Parse the rest of the map data
        match self.version:
            case 0:
                self._parse_map_version_0(hex_data)

            case 1:
                self._parse_map_version_1(hex_data)

            case 2:
                self._parse_map_version_2(hex_data)

            case 152:
                self._parse_map_version_152(hex_data)

            # Default case
            case _:
                raise NotImplementedError(
                    f"Map layout version {self.version} is not supported."
                )

    def _parse_header(self, data: str) -> None:
        """Parse the header of the layout map.

        @param data: The data of the map header.
        """
        _LOGGER.debug("Parsing layout header")

        # The version of the map (0: compressed, 1: uncompressed)
        self.version = int(data[0:2], 16)

        # Get the id of the map
        [self.id] = [
            combine_high_low_to_int(integer[0], integer[1])
            for integer in chunks(hex_to_ints(data[2:6]), 2)
        ]

        self.type = int(data[6:8], 16)  # The type of the map (0: layout, 1: path)
        self.total_count = int(data[36:44], 16)

        # Parse the rest of the data. Code taken from the Tuya Panel Demo
        [
            _,
            _,
            self.width,
            self.height,
            self.origin_x,
            self.origin_y,
            self.map_resolution,
            self.pile_x,
            self.pile_y,
            _,
            _,
            self.length_after_compression,
        ] = [
            combine_high_low_to_int(integer[0], integer[1])
            for integer in chunks(hex_to_ints(data), 2)
        ]

        self.origin_x = shrink_number(self.origin_x)
        self.origin_y = shrink_number(self.origin_y)
        self.pile_x = shrink_number(self.pile_x)
        self.pile_y = shrink_number(self.pile_y)

        self.room_editable = bool(self.type)

        _LOGGER.debug("Finished parsing layout header")

    def _parse_map_version_0(self, data: str):
        """Parse the data of a vacuum map with version 0."""
        # "Normal Version" according to google translate
        # raise NotImplementedError("Map version 0 is not yet supported.")
        # If the data is compressed, decompress it
        if self.length_after_compression:
            max_buffer_length = self.total_count * 8
            encoded_data_array = bytes(hex_to_ints(data[MAP_HEADER_LENGTH:]))
            decoded_data_array = uncompress(encoded_data_array)
            area = self.width * self.height

            map_data_str = "".join(
                "".join(
                    "".join(
                        BITMAP_TYPE_HEX_MAP[x]
                        for x in re.findall(r"\w{2}", format(d, "08b"))
                    )
                )
                for d in decoded_data_array
            )[: area * 2]

            self.rooms = []
            self._map_data_array = bytes.fromhex(map_data_str)
        else:
            raise NotImplementedError("Uncompressed map data is not yet supported.")

    def _parse_map_version_1(self, data: str):
        """Parse the data of a vacuum map with version 1."""
        # "Partition Version" according to google translate

        # If the data is compressed, decompress it
        if self.length_after_compression:
            area = self.width * self.height
            info_length = MAP_HEADER_LENGTH + self.total_count * 2
            encoded_data_array = bytes(hex_to_ints(data[MAP_HEADER_LENGTH:info_length]))
            max_buffer_length = self.total_count * 4
            decoded_data_array = uncompress(encoded_data_array)
            self._map_data_array = decoded_data_array[:area]
            map_room_array = decoded_data_array[area:]

            rooms = Room.parse_rooms(map_room_array.hex())

            for room in rooms:
                _LOGGER.debug(vars(room))

            self.rooms = rooms

        else:
            raise NotImplementedError("Uncompressed map data is not yet supported.")

    def _parse_map_version_2(self, data: str):
        """Parse the data of a vacuum map with version 2."""
        # "Floor Material Version" according to google translate
        raise NotImplementedError("Map version 2 is not yet supported.")

    def _parse_map_version_152(self, data: str):
        """Parse the data of a vacuum map with version 152.

        Seen on some rebranded/newer Tuya vacuums (ex. Kabum "Robô Aspirador
        de Pó 700"). Structurally like version 1, but there's no
        total_count/length_after_compression trailer in the header, and the
        decompressed bitmap has no trailing room data.
        """
        area = self.width * self.height
        encoded_data_array = bytes(hex_to_ints(data[MAP_HEADER_LENGTH_V152:]))
        decoded_data_array = uncompress(encoded_data_array)
        self._map_data_array = decoded_data_array[:area]
        self.rooms = []

    def to_image(self) -> Image.Image:
        """Convert the map to an image.

        Taken from tuya_cloud_map_extractor.
        """
        _LOGGER.debug("Converting layout to image")

        pixels = []
        colors = {
            # "bg_color": default_colors.v1.get("bg_color"),
            "bg_color": ImageColor.getcolor("#006ee6", "RGB"),
            # "wall_color": default_colors.v1.get("wall_color"),
            "wall_color": ["50", "50", "50"],
            # "fun_color": default_colors.v1.get("room_color"),
            "fun_color": ["200", "200", "200"],
        }
        seen_pixel_types = set()
        # This actually works perfectly, what?
        for room in self.rooms:
            colors["room_color_" + str(room.id)] = ImageColor.getcolor(
                # If the room id is higher then the amount of colors, wrap around
                ORIGIN_MAP_COLOR[room.id % len(ORIGIN_MAP_COLOR)],
                "RGB",
            )

        for height_counter in range(self.height):
            line = []
            for width_counter in range(self.width):
                pixel_type = pixel_types.v1.get(
                    self._map_data_array[width_counter + height_counter * self.width]
                )
                pixel = colors.get(pixel_type)
                if not pixel:
                    pixel = (20, 20, 20)
                    if pixel_type not in seen_pixel_types:
                        print(f"Unknown pixel type: {pixel_type}")
                        seen_pixel_types.add(pixel_type)
                line.append(pixel)
            pixels.append(line)

        image = Image.fromarray(np.array(pixels, dtype=np.uint8))
        _LOGGER.debug("Finished converting layout to image")
        return image
